### ISSUE TITLE
Better error handling if no database is set up 

### ISSUE THREAD

**Issue by mikemhenry** [openforcefield/fah-alchemy#50]
Currently, this is what happens if a user runs `fah-alchemy database check`

```
$ fah-alchemy database check
Traceback (most recent call last):
  File "/home/mmh/miniconda3/envs/fah-alchemy/bin/fah-alchemy", line 33, in <module>
    sys.exit(load_entry_point('fah-alchemy', 'console_scripts', 'fah-alchemy')())
  File "/home/mmh/miniconda3/envs/fah-alchemy/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/mmh/miniconda3/envs/fah-alchemy/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/mmh/miniconda3/envs/fah-alchemy/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mmh/miniconda3/envs/fah-alchemy/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mmh/miniconda3/envs/fah-alchemy/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mmh/miniconda3/envs/fah-alchemy/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/mmh/Projects/fah-alchemy/fah_alchemy/cli.py", line 200, in check
    settings = get_settings_from_options(cli_values, Neo4jStoreSettings)
  File "/home/mmh/Projects/fah-alchemy/fah_alchemy/cli.py", line 29, in get_settings_from_options
    return settings_cls(**update)
  File "pydantic/env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 3 validation errors for Neo4jStoreSettings
NEO4J_URL
  field required (type=value_error.missing)
NEO4J_USER
  field required (type=value_error.missing)
NEO4J_PASS
  field required (type=value_error.missing)
```

We should probably catch the error and give a less verbose error message (could be done on the pedantic level)

**Comment by hmacdope** [comment]
IMO I think this is mostly caused by not having `required=True` on the click arguments, and so you an just feed a bunch of `None` to pydantic by accident. I can try actually requiring the arguments be present with click and then see if docker-compose still works.

**Comment by hmacdope** [comment]
But on the other hand it would still be super beneficial to have a clear message that the DB isn't up.
